### ISSUE TITLE
geometry

### ISSUE THREAD

**Issue by morganherlocker** [cutting-room-floor/geojson-cover#3]
- geometry() should be geometryIndexes()
- add geometryGeojson() to bring geometry covers in line with bbox covers

**Comment by morganherlocker** [comment]
- polygonGeojson support https://github.com/mapbox/geojson-cover/commit/a3d64ba43ea2fe3630112ea147f63a9a3842c6ad
- Need to get lines working. Currently not supported for geojson or indexes.

**Comment by morganherlocker** [comment]
Also needs to implement [pointGeoJSON](https://github.com/mapbox/geojson-cover/blob/master/index.js#L63)

**Comment by tmcw** [comment]
Hm, these should be separate issues, right?

**Comment by morganherlocker** [comment]
yep. split:

https://github.com/mapbox/geojson-cover/issues/6 << lines
https://github.com/mapbox/geojson-cover/issues/5 << points
