### ISSUE TITLE
multigeometry cover

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/geojson-cover#4]
this can probably use https://github.com/mapbox/geojson-flatten

**Comment by morganherlocker** [comment]
It also would not be too difficult to do this in c++ and use the native s2PolygonBuilder.

**Comment by morganherlocker** [comment]
node-s2 and geojson-cover now support multipolygons. 

Input:
![img](https://dl.dropbox.com/s/ygy1s29fbwwh0cz/Screenshot%202014-07-28%2016.21.27.png)
Output:
![img](https://dl.dropbox.com/s/6l1u2anka2mtlj8/Screenshot%202014-07-28%2016.20.58.png)
